/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import ru.eltex.database.DefaultSchema;
import ru.eltex.database.tables.records.DeveloperstableRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Developerstable extends TableImpl<DeveloperstableRecord> {

    private static final long serialVersionUID = -707046152;

    /**
     * The reference instance of <code>developersTable</code>
     */
    public static final Developerstable DEVELOPERSTABLE = new Developerstable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeveloperstableRecord> getRecordType() {
        return DeveloperstableRecord.class;
    }

    /**
     * The column <code>developersTable.id</code>.
     */
    public final TableField<DeveloperstableRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>developersTable.name</code>.
     */
    public final TableField<DeveloperstableRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>developersTable.age</code>.
     */
    public final TableField<DeveloperstableRecord, Short> AGE = createField("age", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>developersTable.phone</code>.
     */
    public final TableField<DeveloperstableRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(11), this, "");

    /**
     * Create a <code>developersTable</code> table reference
     */
    public Developerstable() {
        this(DSL.name("developersTable"), null);
    }

    /**
     * Create an aliased <code>developersTable</code> table reference
     */
    public Developerstable(String alias) {
        this(DSL.name(alias), DEVELOPERSTABLE);
    }

    /**
     * Create an aliased <code>developersTable</code> table reference
     */
    public Developerstable(Name alias) {
        this(alias, DEVELOPERSTABLE);
    }

    private Developerstable(Name alias, Table<DeveloperstableRecord> aliased) {
        this(alias, aliased, null);
    }

    private Developerstable(Name alias, Table<DeveloperstableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeveloperstableRecord> getPrimaryKey() {
        return Internal.createUniqueKey(ru.eltex.database.tables.Developerstable.DEVELOPERSTABLE, "KEY_developersTable_PRIMARY", ru.eltex.database.tables.Developerstable.DEVELOPERSTABLE.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeveloperstableRecord>> getKeys() {
        return Arrays.<UniqueKey<DeveloperstableRecord>>asList(
              Internal.createUniqueKey(ru.eltex.database.tables.Developerstable.DEVELOPERSTABLE, "KEY_developersTable_PRIMARY", ru.eltex.database.tables.Developerstable.DEVELOPERSTABLE.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Developerstable as(String alias) {
        return new Developerstable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Developerstable as(Name alias) {
        return new Developerstable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Developerstable rename(String name) {
        return new Developerstable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Developerstable rename(Name name) {
        return new Developerstable(name, null);
    }
}
