/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.eltex.database.tables.Joinmanagersalestable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JoinmanagersalestableRecord extends TableRecordImpl<JoinmanagersalestableRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 2063353487;

    /**
     * Setter for <code>joinManagerSalesTable.idManager</code>.
     */
    public void setIdmanager(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>joinManagerSalesTable.idManager</code>.
     */
    public Integer getIdmanager() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>joinManagerSalesTable.idSale</code>.
     */
    public void setIdsale(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>joinManagerSalesTable.idSale</code>.
     */
    public Integer getIdsale() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Joinmanagersalestable.JOINMANAGERSALESTABLE.IDMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Joinmanagersalestable.JOINMANAGERSALESTABLE.IDSALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdmanager();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdsale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdmanager();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdsale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JoinmanagersalestableRecord value1(Integer value) {
        setIdmanager(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JoinmanagersalestableRecord value2(Integer value) {
        setIdsale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JoinmanagersalestableRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JoinmanagersalestableRecord
     */
    public JoinmanagersalestableRecord() {
        super(Joinmanagersalestable.JOINMANAGERSALESTABLE);
    }

    /**
     * Create a detached, initialised JoinmanagersalestableRecord
     */
    public JoinmanagersalestableRecord(Integer idmanager, Integer idsale) {
        super(Joinmanagersalestable.JOINMANAGERSALESTABLE);

        set(0, idmanager);
        set(1, idsale);
    }
}
