/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.eltex.database.tables.Langstable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangstableRecord extends UpdatableRecordImpl<LangstableRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -140825770;

    /**
     * Setter for <code>langsTable.idLang</code>.
     */
    public void setIdlang(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>langsTable.idLang</code>.
     */
    public Integer getIdlang() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>langsTable.langName</code>.
     */
    public void setLangname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>langsTable.langName</code>.
     */
    public String getLangname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Langstable.LANGSTABLE.IDLANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Langstable.LANGSTABLE.LANGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdlang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLangname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdlang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLangname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangstableRecord value1(Integer value) {
        setIdlang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangstableRecord value2(String value) {
        setLangname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangstableRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangstableRecord
     */
    public LangstableRecord() {
        super(Langstable.LANGSTABLE);
    }

    /**
     * Create a detached, initialised LangstableRecord
     */
    public LangstableRecord(Integer idlang, String langname) {
        super(Langstable.LANGSTABLE);

        set(0, idlang);
        set(1, langname);
    }
}
