/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Joinmanagersalestable implements Serializable {

    private static final long serialVersionUID = 1049531273;

    private final Integer idmanager;
    private final Integer idsale;

    public Joinmanagersalestable(Joinmanagersalestable value) {
        this.idmanager = value.idmanager;
        this.idsale = value.idsale;
    }

    public Joinmanagersalestable(
        Integer idmanager,
        Integer idsale
    ) {
        this.idmanager = idmanager;
        this.idsale = idsale;
    }

    public Integer getIdmanager() {
        return this.idmanager;
    }

    public Integer getIdsale() {
        return this.idsale;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Joinmanagersalestable (");

        sb.append(idmanager);
        sb.append(", ").append(idsale);

        sb.append(")");
        return sb.toString();
    }
}
