/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Joindeveloperlangtable implements Serializable {

    private static final long serialVersionUID = 411847354;

    private final Integer iddeveloper;
    private final Integer idlang;

    public Joindeveloperlangtable(Joindeveloperlangtable value) {
        this.iddeveloper = value.iddeveloper;
        this.idlang = value.idlang;
    }

    public Joindeveloperlangtable(
        Integer iddeveloper,
        Integer idlang
    ) {
        this.iddeveloper = iddeveloper;
        this.idlang = idlang;
    }

    public Integer getIddeveloper() {
        return this.iddeveloper;
    }

    public Integer getIdlang() {
        return this.idlang;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Joindeveloperlangtable (");

        sb.append(iddeveloper);
        sb.append(", ").append(idlang);

        sb.append(")");
        return sb.toString();
    }
}
