/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Langstable implements Serializable {

    private static final long serialVersionUID = -14313294;

    private final Integer idlang;
    private final String  langname;

    public Langstable(Langstable value) {
        this.idlang = value.idlang;
        this.langname = value.langname;
    }

    public Langstable(
        Integer idlang,
        String  langname
    ) {
        this.idlang = idlang;
        this.langname = langname;
    }

    public Integer getIdlang() {
        return this.idlang;
    }

    public String getLangname() {
        return this.langname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Langstable (");

        sb.append(idlang);
        sb.append(", ").append(langname);

        sb.append(")");
        return sb.toString();
    }
}
