/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Salestable implements Serializable {

    private static final long serialVersionUID = -215174343;

    private final Integer idsale;
    private final String  nameproduct;
    private final Integer priceproduct;

    public Salestable(Salestable value) {
        this.idsale = value.idsale;
        this.nameproduct = value.nameproduct;
        this.priceproduct = value.priceproduct;
    }

    public Salestable(
        Integer idsale,
        String  nameproduct,
        Integer priceproduct
    ) {
        this.idsale = idsale;
        this.nameproduct = nameproduct;
        this.priceproduct = priceproduct;
    }

    public Integer getIdsale() {
        return this.idsale;
    }

    public String getNameproduct() {
        return this.nameproduct;
    }

    public Integer getPriceproduct() {
        return this.priceproduct;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Salestable (");

        sb.append(idsale);
        sb.append(", ").append(nameproduct);
        sb.append(", ").append(priceproduct);

        sb.append(")");
        return sb.toString();
    }
}
